
^https:\/\/www\.52pojie\.cn\/home\.php\? url script-request-header https://raw.githubusercontent.com/theload9638/myScripts/main/task/52pj.js
^https?:\/\/www\.53dushu\.com\/home\.php\? url script-request-header https://raw.githubusercontent.com/theload9638/myScripts/main/task/53read.js

hostname = www.52pojie.cn,www.53dushu.com