
^https?:\/\/www\.53dushu\.com\/home\.php\? url script-request-header https://raw.githubusercontent.com/theload9638/myScripts/main/task/53read.js
^https:\/\/b2kk\.brs5d7fw\.com\/home\.php\? url script-request-header https://raw.githubusercontent.com/theload9638/myScripts/main/task/shb.js
^https:\/\/sxsy18\.com\/home\.php\? url script-request-header https://raw.githubusercontent.com/theload9638/myScripts/main/task/sxsy.js

hostname = b2kk.brs5d7fw.com,www.53dushu.com,sxsy18.com