
^https?:\/\/www\.dushuh\.com\/home\.php\? url script-request-header https://raw.githubusercontent.com/theload9638/myScripts/main/task/53read.js
^https:\/\/vfd3\.vdf5ge5a\.com\/home\.php\? url script-request-header https://raw.githubusercontent.com/theload9638/myScripts/main/task/shb.js
^https:\/\/sxsy18\.com\/home\.php\? url script-request-header https://raw.githubusercontent.com/theload9638/myScripts/main/task/sxsy.js

hostname = vfd3.vdf5ge5a.com,www.dushuh.com,sxsy18.com