#aliyun-pan
  #更新
^https?:\/\/user\.alipan\.com\/userBiz\/.*\/updateWindow\/getLatestVersion url jsonjq-response-body '.isForceUpdate=false'
  #首页banner
^https?:\/\/bizapi\.alipan\.com\/apps\/.*\/user\/home\/widgets url jsonjq-response-body '.|del(.banners)'
^https?:\/\/member\.alipan\.com\/.*\/users\/onboard_list url jsonjq-response-body '.result=[]'
^https?:\/\/member\.alipan\.com\/.*\/config\/customCapsule url jsonjq-response-body '.|del(.result.desktop)|del(.result.applet)|del(.result.web)|del(.result.client)|.result.client={"videoSetting":{"support_ting_wu":false, "use_youku_pip":true,"subtitle_auto_search":0.5}}'
  #容量限制下载解除和提示删除
^https?:\/\/api\.alipan\.com\/adrive\/.*\/user\/getUserCapacityInfo url jsonjq-response-body '.user_capacity_limit_details.limit_download=false|.user_capacity_limit_details.limit_scenes=[]|.user_capacity_limit_details.limit_consume=false|.capacity_level_info.capacity_type="normal"'
  #试用状态开启,解除播放需要svip
^https?:\/\/api\.alipan\.com\/business\/.*\/users\/feature\/list url jsonjq-response-body 'walk(if type == "object" and has("intercept") then .intercept = false else . end)'
^https?:\/\/api\.alipan\.com\/business\/.*\/users\/benefit\/detail url jsonjq-response-body '.trialStatus="allowTrial"|.trialDuration=999'

hostname = *.alipan.com