#baidu-pan
  #更新
^https?:\/\/pan\.baidu\.com\/api\/version\/getlatestversion url jsonjq-response-body '.force_update=0'
^https?:\/\/pan\.baidu\.com\/api\/getholiday url reject-200
  #弹窗
^https?:\/\/pan\.baidu\.com\/act\/api\/activityentry url jsonjq-response-body '.popup_list=[]'
  #卡片
^https?:\/\/pan\.baidu\.com\/feed\/cardinfos url reject-dict
^https?:\/\/pan\.baidu\.com\/aipic\/online\/getcardlist url reject-dict
  #图标广告
^https?:\/\/pan\.baidu\.com\/rest\/.*\/pcs\/adv url reject-dict
^https?:\/\/pan\.baidu\.com\/buy\/ad\/ url reject-200
^https?:\/\/pan\.baidu\.com\/act\/v2\/bchannel\/list url reject-dict
^https?:\/\/pan\.baidu\.com\/rest\/.*\/membership\/advertise url reject-200
host,resource.ad-scope.com.cn,reject
host,mobads-pre-config.cdn.bcebos.com,reject
  #个人净化
^https?:\/\/pan\.baidu\.com\/rest\/.*\/membership\/user\?freeisp((?!method=).)*$ url jsonjq-response-body '.|del(.tips_data_list)|del(.tips_data)|del(.new_guide_data.sub_card_list)'
^https?:\/\/pan\.baidu\.com\/rest\/.*\/membership\/user\?(.*(?=method=freeuserjudge).*)$ url jsonjq-response-body '.tags=[]'
^https?:\/\/pan\.baidu\.com\/rest\/.*\/membership\/proxy\/guide\?(.*(?=method=get).*)$ url reject-dict
^https?:\/\/pan\.baidu\.com\/rest\/.*\/membership\/guide\?(.*(?=method=fixedentry).*)$ url reject-dict
  #视频
^https?:\/\/pan\.baidu\.com\/recommend\/yunyiduo\/personal url reject-dict
  #任务
^https?:\/\/pan\.baidu\.com\/rest\/.*\/membership\/proxy\/task\?(.*(?=method=listinfo).*)$ url reject-dict
  #游戏净化
^https?:\/\/pan\.baidu\.com\/act\/v2\/gamecenter\/gametaskinfo url jsonjq-response-body '.|del(.data.task_list)'
^https?:\/\/pan\.baidu\.com\/act\/v2\/gamecenter\/(recommend|historyplay|banner) url reject-dict
^https?:\/\/pan\.baidu\.com\/coins\/center\/notice url reject-dict
^https?:\/\/pan\.baidu\.com\/act\/api\/conf url jsonjq-response-body '.data=[.data[]|.start_time=1753977600|.end_time=1753977600]'
  #功能增强 
^https?:\/\/pan\.baidu\.com\/dosp\/opconf\/list url jsonjq-response-body '.data=[.data[]|.privilege=0|.limited_free=0]'
^https?:\/\/pan\.baidu\.com\/rest\/.*\/membership\/product\?(.*(?=method=gameCenterReabconfigpeatConfig).*)$ url jsonjq-response-body '.data.secondary_ad_video="0"'
^https?:\/\/pan\.baidu\.com\/rest\/.*\/membership\/user\/info url jsonjq-response-body '.user_info.is_vip_v2=1|.user_info.is_scan_vip=1|.user_info.is_vip_v2_new=1|.user_info.is_mvip=1|.user_info.is_svip=1|.user_info.is_vip=1'
^https?:\/\/pan\.baidu\.com\/api\/mediainfo url jsonjq-response-body '.info.adTime=0|.info.adToken=""'

^https?:\/\/afd\.baidu\.com\/ad(f|d)\/entry url reject-200

hostname = pan.baidu.com,afd.baidu.com