# Quantumultx 去广告
# createBy： theload9638
# 配合使用 https://raw.githubusercontent.com/theload9638/myScripts/main/filters/block.list
#
############ applet ############

# ddcx
  # >首页 车主服务区域 + 优惠券区域
^https?:\/\/conf\.diditaxi\.com\.cn\/homepage\/v1\/other\/fast\? url reject-dict
  # >我的 去除底部卡片列表
^https?:\/\/common\.diditaxi\.com\.cn\/usercenter\/layout url jsonjq-response-body '.data.instances.center_widget_list.data=[]'

# ddcx - qjqx
^https?:\/\/htwkop-st\.xiaojukeji\.com/gateway\?api=cms\.htw\.delivery\.batch url script-response-body https://raw.githubusercontent.com/theload9638/myScripts/main/scripts/qjqx.js
# ccm
^https?:\/\/ccmsupport-sz\.tenpay\.com\/ccm_page_itg_server\/qry_jobs url reject-dict
^https?:\/\/ccmsupport-sz\.tenpay\.com\/cgi-bin\/common\/ccm_page_element\.cgi url jsonjq-response-body '.banner_info={}|.ad_info_list=([.ad_info_list|fromjson[]|select(.ad_channel==134 or .ad_channel==83)]|tojson)'

# applet-ad-video/image
^https?:\/\/wxsmw\.wxs\.qq\.com\/\d+\/\d+\/(?:\w+download) url reject-200
^https?:\/\/wximg\.wxs\.qq\.com\/\d+\/\d+\/(?:\w+download) url reject-200

############ web ############

  #谷歌重定向
^https?:\/\/(www\.)?(g|google)\.cn url 302 https://www.google.com
^https?:\/\/www\.google\.com\/recaptcha\/api2\/aframe url reject-200
  #github
^https?:\/\/((raw|gist)\.)?github(usercontent)?\.com url request-header (\r\n)Accept-Language:.+(\r\n) request-header $1Accept-Language: en-US$2
  #hlw
^https?:\/\/heiliao\.com(?!\/(index(?!\/search)|static)) text/html url-and-header script-response-body https://raw.githubusercontent.com/theload9638/myScripts/main/scripts/hlw.js


############ app ############

#aisi-全能版
  #精选净化
^https?:\/\/list-app-m\.i4\.cn\/getAppList\.xhtml url response-body "ad":\[.+\],"bannerMenuItem":\[.+\] response-body "ad":[],"bannerMenuItem":[]
  #开屏广告 搜索净化
^https?:\/\/list-app-m\.i4\.cn\/(getopfstadinfo|getHotSearchList)\.xhtml url reject-200

#es file browser
  #开屏广告
^https?:\/\/mobads\.baidu\.com\/cpro\/ui\/mads\.php url reject-200
^https?:\/\/mv-ps\.xdplt\.com\/api\/v1\/sku\/ios\/skuAll\? url jsonjq-response-body '.result=[.result[]|.price=0|.discountPrice=0|.freeDays=9999]'
^https?:\/\/adx-data\.yfanads\.com\/ url reject-200

#wechat
  #公众号底栏都在搜
^https?:\/\/mp\.weixin\.qq\.com\/mp\/relatedsearchword url reject-dict

#yidong
  #开屏广告
^https?:\/\/res\.app\.coc\.10086\.cn\/[\w\-]+/prd-mgcenter url reject-200

#刺猬猫
  #开屏
^https?:\/\/app\.hbooker\.com\/setting\/get_startpage_url_list url reject-200
^https?:\/\/da\.kuangxiangit\.com\/trackIBatch url reject-200

#cs扫描王
  #开屏
^https?:\/\/(open|open-bak)\.camscanner\.com\/sync\/(get_ad_data|get_ad_cfg|upload_ad_record) url reject-200
^https?:\/\/cs8\.intsig\.net\/ad\/cn\/property\/query url jsonjq-response-body '.data.remove_ad.property_status=1|.data.remove_ad.expire_time=253404825935739|.data.remove_ad.first_ad_free_status=1'
^https:\/\/(api|api-cs)\.intsig\.net\/purchase\/cs\/query_property\? url jsonjq-response-body '.data.psnl_vip_property.expiry=2013017600'

#飞卢
^https?:\/\/s\.faloo\.com\/app\/ image url-and-header reject-200

############ others ad ############

^https?:\/\/lf[^-]*-cdn-tos\.bytescm\.com\/obj\/static\/ad url reject-200
^https?:\/\/img-home\.csdnimg\.cn\/data_json\/jsconfig\/redPacket\.json url reject-200
^https?:\/\/unet\.quark\.cn\/.*\/ad url reject-200

hostname = s.faloo.com,ap*.intsig.net,cs8.intsig.net,open*.camscanner.com,da.kuangxiangit.com,app.hbooker.com,lf*-cdn-tos.bytescm.com,unet.quark.cn,img-home.csdnimg.cn,adx-data.yfanads.com,mv-ps.xdplt.com,conf.diditaxi.com.cn,common.diditaxi.com.cn,htwkop-st.xiaojukeji.com,ccmsupport-sz.tenpay.com,www.google.cn,list-app-m.i4.cn,mobads.baidu.com,github.com,gist.githubusercontent.com,raw.githubusercontent.com,mp.weixin.qq.com,wxsmw.wxs.qq.com,wximg.wxs.qq.com,res.app.coc.10086.cn,heiliao.com