# gpy 解锁

  #更新
^https?:\/\/ke\.gupaoedu\.cn\/.*\/api\/ke\/app\/checkUpdate url jsonjq-response-body '.data.forced=false'
  #banner
^https?:\/\/ke\.gupaoedu\.cn\/.*\/api\/ke\/index\/banners url reject-dict
^https?:\/\/ke\.gupaoedu\.cn\/.*\/api\/ke\/course\/category\/info\/banner\/page url reject-dict
  #课程
^https?:\/\/ke\.gupaoedu\.cn\/.*\/api\/ke\/course\/curriculum\/page url jsonjq-response-body 'walk(if type == "object" and has("price") then .isFreeAccess=1|.price=0|.freeAccessLevel=1 else . end)'
^https?:\/\/ke\.gupaoedu\.cn\/.*\/api\/ke\/.*\/curriculum\/detail url jsonjq-response-body '.data.isFreeAccess=1|.data.freeAccessLevel=1|.data.price=0'
^https?:\/\/ke\.gupaoedu\.cn\/.*\/api\/ke\/((index\/everybody_learning)|(.*\/curriculum\/outline)) url jsonjq-response-body 'walk(if type == "object" and has("isFreeAccess") then .isFreeAccess=1|if has("price") then .price=0 else . end|.freeAccessLevel=1 else . end)'
  #内推显示
^https?:\/\/ke\.gupaoedu\.cn\/.*\/api\/ke\/user\/(?=.*simpleInfo) url jsonjq-response-body '.data.isVip=1|.data.inviteAuth=1'

hostname = ke.gupaoedu.cn