# jm simple clear
# hostname = www.cdnbea.org,www.cdnsha.org,www.cdnzack.cc,www.cdnntr.cc,www.cdnhth.club,www.cdngwc.cc,www.cdngwc.club,
#            www.cdngwc.net,www.cdnhjk.cc,
#            cdn-msp*.jmapiproxy*.*,cn-appdata.jmapiproxy*.cc,cdn-msp*.jmdanjonproxy*.*,tencent.jmdanjonproxy.xyz,
#            cdn-msp*.18comic.*
#            s.chnsrv.com,a.chnsrv.com

# jm app

  #入口和章节净化
^https?:\/\/www\.cdn(bea|sha|zack|ntr|gwc|hth|hjk)\.(org|cc|net|club)\/ad_template url script-response-body https://raw.githubusercontent.com/theload9638/myScripts/main/scripts/jm.js
^https?:\/\/www\.cdn(bea|sha|zack|ntr|gwc|hth|hjk)\.(org|cc|net|club)\/chapter_view_template url script-response-body https://raw.githubusercontent.com/theload9638/myScripts/main/scripts/novelAd.js
  #入口广告/游戏/影片
^https?:\/\/www\.cdn(bea|sha|zack|ntr|gwc|hth|hjk)\.(org|cc|net|club)\/(advertise|allgames|videos) url reject-dict
  #logo
^https?:\/\/(cdn-msp(\d)*|cn-appdata|tencent)\.(jmapiproxy|jmdanjonproxy|18comic)(\d)*\.(cc|vip|xyz|ink|vip)\/media\/logo url reject-200
  #界面净化
^https?:\/\/(cdn-msp(\d)*|cn-appdata|tencent)\.(jmapiproxy|jmdanjonproxy|18comic)(\d)*\.(cc|vip|xyz|ink|vip)\/static\/resources\/images url reject-200
^https?:\/\/(cdn-msp(\d)*|cn-appdata|tencent)\.(jmapiproxy|jmdanjonproxy|18comic)(\d)*\.(cc|vip|xyz|ink|vip)\/static\/resources\/files\/(.*)?\.gif url reject-200
^https?:\/\/s\.chnsrv\.com\/v1\/api\.php url response-body "zones":\[.+\],"renderers":\{.+\} response-body "zones":[],"renderers":{}
^https?:\/\/a\.chnsrv\.com/(.*?)(ad-provider|banner|native)\.js url reject-200

# jm web

^https?:\/\/18comic\.(vip|ink) text/html url-and-header script-response-body https://raw.githubusercontent.com/theload9638/myScripts/main/scripts/novelAd.js

hostname = 18comic.ink,18comic.vip,www.cdnbea.org,www.cdnsha.org,www.cdnzack.cc,www.cdnntr.cc,www.cdnhth.club,www.cdngwc.cc,www.cdngwc.club,www.cdngwc.net,www.cdnhjk.cc,cdn-msp*.jmapiproxy*.*,cn-appdata.jmapiproxy*.cc,cdn-msp*.jmdanjonproxy*.*,cdn-msp*.18comic.*,tencent.jmdanjonproxy.xyz,s.chnsrv.com,a.chnsrv.com