#msb 解锁

^https?:\/\/gateway\.mashibing\.com\/edu-market\/app\/advertisement\/info url reject-dict
^https?:\/\/gateway\.mashibing\.com\/edu-market\/admin\/float\/advertisement\/info url reject-dict
  #更新
^https?:\/\/gateway\.mashibing\.com\/edu-course\/appVersion\/latestVersion url jsonjq-response-body '.data={}'
  #课程
^https?:\/\/gateway\.mashibing\.com\/edu-course\/courseHomePage\/app\/list\/v3 url jsonjq-response-body '.data.content=[.data.content[]|.plateId=0|.vip=false|.buyFlag=true]'
^https?:\/\/gateway\.mashibing\.com\/edu-course\/app\/systemCourse\/course url jsonjq-response-body 'walk(if type == "object" and .isTrial == false then .isTrial=true else . end)|.data.isFreeTrial=1|.data.plateId=0|.data.buyFlag=1|.data.shareState=1|.data.hasState=1|.data.publishStatus=1|.data.price=0|.data.vip=false'
^https?:\/\/gateway\.mashibing\.com\/edu-course\/courseWeb\/info url jsonjq-response-body '.data.plateId=0'
^https?:\/\/gateway\.mashibing\.com\/edu-course\/courseDocumentWeb\/list\/app url jsonjq-response-body 'walk(if type == "object" and .isFree == 0 then .isFree=1 else . end)'

^https?:\/\/gateway\.mashibing\.com\/edu-qa\/app\/question\/detail url jsonjq-response-body '.data.vip=false|.data.isPublic=1|.data.plateId=0'
^https?:\/\/gateway\.mashibing\.com\/edu-qa\/user\/isQaTeacher url jsonjq-response-body '.data=true'

^https?:\/\/gateway\.mashibing\.com\/edu-course\/app\/coursePlate\/list url jsonjq-response-body 'walk(if type == "object" and .plateId == 1 then .plateId=0 else . end)'
^https?:\/\/gateway\.mashibing\.com\/edu-course\/interactive url jsonjq-response-body '.data.isTrial=1'
^https?:\/\/gateway\.mashibing\.com\/edu-live\/pcLive\/findChannelRecordNewestByCache url jsonjq-response-body '.data.viewNum=0|.data.openViewNum=0|.data.price=0'
^https?:\/\/gateway\.mashibing\.com\/edu-course\/courseHomePage\/isHasCourse url jsonjq-response-body '.data=true'

^https?:\/\/gateway\.mashibing\.com\/edu-live\/appLiveSign\/findSignStatus url jsonjq-response-body '.data=true'
^https?:\/\/gateway\.mashibing\.com\/uaa\/user\/(info|getUserInfo) url jsonjq-response-body '.data.isVip=true|.data.internalFlag=true'
^https?:\/\/gateway\.mashibing\.com\/edu-course\/coursePackage\/app url jsonjq-response-body '.data.shareState=1|.data.courseDetail=""|.data.enableRenewal=null|.data.degree=1|.data.isOpenStudyRoadmap=true|walk(if type == "object" and has("plateId") then .plateId=0 else . end)'
^https?:\/\/gateway\.mashibing\.com\/edu-course\/app\/coursePackageVersion url jsonjq-response-body 'walk(if type == "object" and has("enabled") then .enabled=1 else . end)'

^https?:\/\/gateway\.mashibing\.com\/edu-course\/coursePackage url jsonjq-response-body 'walk(if type == "object" and has("isOpenStudyRoadmap") then .isOpenStudyRoadmap=true else . end)'
^https?:\/\/gateway\.mashibing\.com\/edu-course\/courseWeb\/course\/data url jsonjq-response-body '.data=true|.code=200'
^https?:\/\/gateway\.mashibing\.com\/msb-video\/ployv\/playerSafe url jsonjq-response-body '.data=true|.code=200'
^https?:\/\/gateway\.mashibing\.com\/edu-live\/appLiveVideo\/findChannelRecord url jsonjq-response-body '.data.visible=1'
  #问题查看
^https?:\/\/gateway\.mashibing\.com\/edu-qa\/(question|user)\/(hasQuestionPermission|isQaTeacherOrAssistant) url jsonjq-response-body '.data=true'

hostname = gateway.mashibing.com

