# tieba
  #个人中心净化
^https?:\/\/tiebac\.baidu\.com\/c\/u\/user\/profile url script-response-body https://raw.githubusercontent.com/theload9638/myScripts/main/scripts/tieba.js
  #搜索栏净化
^https?:\/\/tiebac?\.baidu\.com\/c\/f\/search\/discover url reject-dict
  #侧边栏净化
^https?:\/\/tiebac\.baidu\.com\/c\/f\/sidebar\/home url jsonjq-response-body '.|del(.vip_banner)|del(.game_center)|del(.tools)'
  #首页-直播banner轮播净化
^https?:\/\/tiebac?\.baidu\.com\/livefeed\/feed url jsonjq-response-body 'del(.data.banner)'
  #小卖部-轮播banner净化
^https?:\/\/tieba\.baidu\.com\/c\/f\/forum\/shopGoodsFeed url jsonjq-response-body '.data.banner_info=[]'
  #弹窗广告
^https?:\/\/tieba\.baidu\.com\/c\/f\/dialog\/showDialog url reject-200
  #快捷历史
^https?:\/\/tieba\.baidu\.com\/c\/f\/forum\/gethistoryforum url jsonjq-response-body '.history_forum=[]'
  #进吧
^https?:\/\/tieba\.baidu\.com\/c\/f\/forum\/forumGuide url jsonjq-response-body '.hot_search=[]'
  #广告
^https?:\/\/afd\.baidu\.com\/ad(f|d)\/entry url reject-200

hostname = tiebac.baidu.com,tieba.baidu.com,afd.baidu.com